version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: automationdb
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: automationdb
      DB_POSTGRESDB_USER: admin
      DB_POSTGRESDB_PASSWORD: password
    depends_on:
      - postgres
